name: loja
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  flutter_staggered_grid_view: ^0.7.0
  cloud_firestore: ^4.16.0
  firebase_analytics: ^10.10.0
  firebase_messaging: ^14.8.0
  another_carousel_pro: ^1.0.2
  transparent_image: ^2.0.1
  scoped_model: ^2.0.0
  path_provider: ^2.1.2
  firebase_auth: ^4.19.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:

  
  uses-material-design: true

  
